server:
  port: 1111

spring:
  application:
    name: STOCK-PRICE-API
  datasource:
    url: jdbc:h2:mem:testDB
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
    management:
    endpoints:
    web:
    exposure:
    include: '*'
